# FROM line is set by build_dockers.sh, don't edit it here
FROM ashedpotatoes/clockwork-plus:v0.11.3.7-slim
COPY references/varpipe.Ref.remove_contam.tar ./ref/Ref.remove_contam.tar
# RUN apt-get install tree -y