# FROM line is set by build_dockers.sh, don't edit it here
FROM ashedpotatoes/clockwork-plus:v0.12.5.3-slim
RUN mkdir ./ref/Ref.remove_contam
COPY references/CDC-varpipe/Ref.remove_contam/ref.fa ./ref/Ref.remove_contam/ref.fa 
COPY references/CDC-varpipe/Ref.remove_contam/ref.fa.fai ./ref/Ref.remove_contam/ref.fa.fai
COPY references/CDC-varpipe/Ref.remove_contam/remove_contam_metadata.tsv ./ref/Ref.remove_contam/remove_contam_metadata.tsv


# it's worth noting that the CDC references were (presumably) created with 0.11.3 of clockwork,
# but we're now using newer clockwork stuff in this image -- that shouldn't change things though