FROM ghcr.io/iqbal-lab-org/clockwork:v0.11.3 
RUN apt-get install tree -y
RUN apt-get install rename -y
RUN cd .. && mkdir fastp && cd fastp && \
    wget http://opengene.org/fastp/fastp.0.23.4 && \
    mv fastp.0.23.4 fastp && chmod a+x ./fastp
ENV PATH=/fastp:$PATH
RUN mkdir ref
COPY references/Ref.H37Rv.tar ./ref/